
# ! for 1m
"maxbuys"   = 2
"pqty"      = [1,1]
"mult"      = 1
"intval"    = 0.0618# 0.09
"rseed"     = 2  # in BASE (ETH)
"runlevels" = 4
"perf5_buy_length" = 32
"perf5_sell_length" = 32
"perf5_sell_lessthan" = -20
"perf5_buy_greaterthan" = 20
"sell_at" = 1.019

# ! for 0m
#"maxbuys"   = 2
#"pqty"      = [0.5,0.5]
#"mult"      = 1
#"intval"    = 0.00618# 0.09
#"rseed"     = 1  # in BASE (ETH)
#"runlevels" = 4
#"perf5_buy_length" = 32
#"perf5_sell_length" = 32
#"perf5_sell_lessthan" = -0
#"perf5_buy_greaterthan" = 0
#"sell_at" = 1.019
