#!/bin/bash

if [ "$1" == "" ]; then
    echo "ERROR: Missing DIR name"
    exit 1
fi


mkdir $1 > /dev/null 2>&1
mkdir $1/configs > /dev/null 2>&1
mkdir $1/assets > /dev/null 2>&1
mkdir $1/data > /dev/null 2>&1
mkdir $1/logs > /dev/null 2>&1
mkdir $1/records > /dev/null 2>&1
mkdir $1/orders > /dev/null 2>&1

cp assets/* $1/assets > /dev/null 2>&1
cp data/*   $1/data   > /dev/null 2>&1


if [ "$2" == "C" ]; then
    echo "INCLUDING 'config.toml'"
    cp *.hcl $1/
else
    echo "NOT INCLUDING 'config.toml'"
fi

cp _session_name.txt  $1/
cp v2.py            $1/
cp lib_v2_globals.py     $1/
cp lib_v2_ohlc.py        $1/
cp lib_v2_listener.py    $1/
cp lib_v2_tests_class.py $1/
cp state.json       $1/
#cp config_0.hcl		    $1/
cp auth_client.py     $1/
cp public_client.py   $1/

cp view.py            $1/
cp gview.py            $1/
cp dbview.py            $1/
cp merge.py           $1/
cp liveview.py        $1/
cp ohlc_backdata.py   $1/
cp README.md           $1/
cp pread.py           $1/
