#!/bin/bash
mysqldump -ujmc -p6kjahsijuhdxhgd jmcap   --add-drop-table > jmcap_DUMP.sql
#! this load everything, overwriting existing data files on teh server
# rsync -avr --delete --exclude-from 'exclude.txt' /home/jw/src/jmcap/v2bot/ jw@duncanstroud.com:/home/jw/src/jmcap/v2bot/

#code
echo "Uploading: *.py"
rsync -avr /home/jw/src/jmcap/v2bot/*.py jw@duncanstroud.com:/home/jw/src/jmcap/v2bot/  > logs/PUB.log 2>&1

#scripts
echo "Uploading: *.sh"
rsync -avr /home/jw/src/jmcap/v2bot/*.sh jw@duncanstroud.com:/home/jw/src/jmcap/v2bot/ >> logs/PUB.log 2>&1

#perf data
echo "Uploading: perf*"
rsync -avr /home/jw/src/jmcap/v2bot/data/perf* jw@duncanstroud.com:/home/jw/src/jmcap/v2bot/data/ >> logs/PUB.log 2>&1

#misc
echo "Uploading: config_template.toml"
rsync -avr /home/jw/src/jmcap/v2bot/config_template.toml jw@duncanstroud.com:/home/jw/src/jmcap/v2bot/ >> logs/PUB.log 2>&1
rsync -avr /home/jw/src/jmcap/v2bot/CRONRUN jw@duncanstroud.com:/home/jw/src/jmcap/v2bot/ >> logs/PUB.log 2>&1

read -n1 -p "Kill remote v2? [y/N]: " cvar
case $cvar in
  y|Y) ssh jw@108.161.133.254 ~/src/jmcap/v2bot/killstream >> logs/PUB.log 2>&1 ;;
  n|N) echo :"Skipping..." ;;
  *) echo dont know ;;
esac

read -p "Send [config.tom]l? [y/N]: " cvar
case $cvar in
  y|Y) scp config.toml  jw@108.161.133.254:src/jmcap/v2bot/ >> logs/PUB.log 2>&1 ;;
  n|N) echo :"Skipping..." ;;
  *) echo dont know ;;
esac

read -p "Send [data/_perf4.json]? [y/N]: " cvar
case $cvar in
  y|Y) scp data/_perf4.json jw@108.161.133.254:src/jmcap/v2bot/data >> logs/PUB.log 2>&1 ;;
  n|N) echo :"Skipping..." ;;
  *) echo dont know ;;
esac

echo "Checking for errors..."
grep rsync logs/PUB.log
