#!/bin/bash
mysqldump -ujmc -p6kjahsijuhdxhgd jmcap   --add-drop-table > jmcap_DUMP.sql
#! this load everything, overwriting existing data files on teh server
# rsync -avr --delete --exclude-from 'exclude.txt' /home/jw/src/jmcap/v2bot/ jw@duncanstroud.com:/home/jw/src/jmcap/v2bot/

#code
rsync -avr /home/jw/src/jmcap/v2bot/*.py jw@duncanstroud.com:/home/jw/src/jmcap/v2bot/

#perf data
rsync -avr /home/jw/src/jmcap/v2bot/data/perf* jw@duncanstroud.com:/home/jw/src/jmcap/v2bot/data/

